;; extends

; (("assert"       @keyword) (#set! conceal "?"))
; (("continue"     @keyword) (#set! conceal "C"))
; (("break"        @keyword) (#set! conceal "B"))
; (("del"          @keyword) (#set! conceal "D"))
; (("yield"        @keyword) (#set! conceal "Y"))
; (("pass"         @keyword) (#set! conceal "P"))
; ((yield ("from") @keyword) (#set! conceal "F"))
; (("with"         @keyword) (#set! conceal "w"))
; (("return"       @keyword) (#set! conceal "R"))
; (("global"       @keyword) (#set! conceal "G"))
; (("class"        @keyword) (#set! conceal "c"))
; (("else"         @conditional) (#set! conceal "e"))
; (("if"           @conditional) (#set! conceal "?"))
; (("elif"         @conditional) (#set! conceal "e"))
; (("def"          @keyword.function) (#set! conceal "f"))
; (("import"       @include) (#set! conceal "i"))
; ((import_from_statement ("from") @include) (#set! conceal "f"))
; (("while"        @repeat) (#set! conceal "W"))

(("lambda"       @include) (#set! conceal "λ"))
(("in"           @keyword) (#set! conceal "∈"))
(("and"          @keyword.operator) (#set! conceal "⩓"))
(("or"           @keyword.operator) (#set! conceal "⩔"))
(("not"          @keyword.operator) (#set! conceal "!"))
