---@diagnostic disable-next-line: unused-local
local other = {
    "-W",
    "clippy::expl_impl_clone_on_copy",

    "-W",
    "clippy::fallible_impl_from",

    "-W",
    "clippy::fn_params_excessive_bools",

    "-W",
    "clippy::fn_to_numeric_cast_any",

    "-W",
    "clippy::implied_bounds_in_impls",
    "-W",
    "clippy::imprecise_flops",
    "-W",
    "clippy::inconsistent_struct_constructor",

    "-W",
    "clippy::inline_always",
    "-W",
    "clippy::inline_asm_x86_att_syntax",
    "-W",
    "clippy::inline_asm_x86_intel_syntax",

    "-W",
    "clippy::items_after_statements",

    "-W",
    "clippy::macro_use_imports",
    "-W",
    "clippy::many_single_char_names",

    "-W",
    "clippy::mismatching_type_param_order",
    "-W",
    "clippy::multiple_inherent_impl",

    "-W",
    "clippy::mixed_read_write_in_expression",
    "-W",
    "clippy::module_name_repetitions",
    "-W",
    "clippy::modulo_arithmetic",
    "-W",
    "clippy::naive_bytecount",

    "-W",
    "clippy::negative_feature_names",
    "-W",
    "clippy::no_effect_underscore_binding",
    "-W",
    "clippy::no_mangle_with_rust_abi",
    "-W",
    "clippy::non_send_fields_in_send_ty",
    "-W",
    "clippy::nonstandard_macro_braces",
    "-W",
    "clippy::option_option",
    "-W",
    "clippy::or_fun_call",
    "-W",
    "clippy::partial_pub_fields",
    "-W",
    "clippy::path_buf_push_overwrite",
    "-W",
    "clippy::pattern_type_mismatch",

    "-W",
    "clippy::single_call_fn",
    "-W",
    "clippy::single_char_lifetime_names",
    "-W",
    "clippy::single_match_else",

    "-W",
    "clippy::exhaustive_enums",
    "-W",
    "clippy::exhaustive_structs",
    -- "-W",
    -- "clippy::suspicious_operation_groupings",
    -- "-W",
    -- "clippy::suspicious_xor_used_as_pow",
    "-W",
    "clippy::too_many_lines",
    "-W",
    "clippy::trailing_empty_array",

    "-W",
    "clippy::transmute_undefined_repr",

    "-W",
    "clippy::used_underscore_binding",

    "-W",
    "clippy::wildcard_dependencies",
    "-W",
    "clippy::wildcard_enum_match_arm",
    "-W",
    "clippy::wildcard_imports",
}

return {
    "--no-deps",
    "--",

    ---String
    "-W",
    "clippy::str_to_string",
    -- "-W",
    -- "clippy::string_add",
    "-W",
    "clippy::string_add_assign",
    "-W",
    "clippy::string_lit_as_bytes",
    -- "-W",
    -- "clippy::string_lit_chars_any",
    "-W",
    "clippy::string_slice",
    "-W",
    "clippy::string_to_string",
    -- "-W",
    -- "clippy::format_push_string",
    "-W",
    "clippy::inefficient_to_string",
    "-W",
    "clippy::manual_string_new",
    "-W",
    "clippy::needless_raw_strings",
    ---

    ---map
    "-W",
    "clippy::filter_map_next",
    "-W",
    "clippy::flat_map_option",
    "-W",
    "clippy::map_err_ignore",
    "-W",
    "clippy::map_unwrap_or",
    "-W",
    "clippy::zero_sized_map_values",
    ---

    ---iter
    "-W",
    "clippy::maybe_infinite_iter",
    "-W",
    "clippy::from_iter_instead_of_collect",
    "-W",
    "clippy::iter_not_returning_iterator",
    "-W",
    "clippy::iter_on_empty_collections",
    "-W",
    "clippy::iter_on_single_items",
    "-W",
    "clippy::iter_with_drain",
    ---

    "-W",
    "clippy::let_underscore_untyped",
    "-W",
    "clippy::useless_let_if_seq",
    -- "-W",
    -- "clippy::option_if_let_else",
    -- "-W",
    -- "clippy::else_if_without_else", -- lint `else{}`: in end
    "-W",
    "clippy::equatable_if_let",
    "-W",
    "clippy::bool_to_int_with_if",
    "-W",
    "clippy::if_not_else",
    "-W",
    "clippy::if_then_some_else_none",

    "-W",
    "clippy::manual_assert",
    "-W",
    "clippy::manual_clamp",
    "-W",
    "clippy::manual_instant_elapsed",
    "-W",
    "clippy::manual_let_else",
    "-W",
    "clippy::manual_ok_or",

    "-W",
    "clippy::decimal_literal_representation",
    -- "-W",
    -- "clippy::non_ascii_literal",
    "-W",
    "clippy::unreadable_literal",
    "-W",
    "clippy::unseparated_literal_suffix", -- 1_u32
    -- "-W",
    -- "clippy::separated_literal_suffix",-- 1u32
    -- "-W",
    -- "clippy::default_numeric_fallback",

    "-W",
    "clippy::redundant_clone",
    -- "-W",
    -- "clippy::redundant_closure_for_method_calls",
    "-W",
    "clippy::redundant_else",
    "-W",
    "clippy::redundant_feature_names",
    "-W",
    "clippy::redundant_pub_crate",
    -- "-W",
    -- "clippy::redundant_type_annotations",

    -- "-W",
    -- "clippy::unwrap_used",
    -- "-W",
    -- "clippy::get_unwrap",
    "-W",
    "clippy::unwrap_in_result",
    -- "-W",
    -- "clippy::expect_used",

    ----------------------------------------
    -- "-W",
    -- "clippy::absolute_paths",

    -- "-W",
    -- "clippy::missing_trait_methods",
    -- "-W",
    -- "clippy::missing_asserts_for_indexing",
    -- "-W",
    -- "clippy::missing_assert_message",
    -- "-W",
    -- "clippy::missing_enforced_import_renames",
    -- "-W",
    -- "clippy::missing_fields_in_debug",
    -- "-W",
    -- "clippy::missing_inline_in_public_items",
    -- "-W",
    -- "clippy::missing_errors_doc",
    -- "-W",
    -- "clippy::missing_panics_doc",
    -- "-W",
    -- "clippy::missing_docs_in_private_items",
    "-W",
    "clippy::unnecessary_safety_doc",
    "-W",
    "clippy::doc_link_with_quotes",
    "-W",
    "clippy::doc_markdown",
    "-W",
    "clippy::empty_line_after_doc_comments",

    -- "-W",
    -- "clippy::must_use_candidate",
    -- "-W",
    -- "clippy::return_self_not_must_use",
    -- "-W",
    -- "clippy::let_underscore_must_use",

    -- "-W",
    -- "clippy::multiple_unsafe_ops_per_block",
    -- "-W",
    -- "clippy::undocumented_unsafe_blocks",
    -- "-W",
    -- "clippy::unsafe_derive_deserialize",

    -- "-W",
    -- "clippy::question_mark_used",
    -- "-W",
    -- "clippy::min_ident_chars",
    -- "-W",
    -- "clippy::mod_module_files",
    -- "-W",
    -- "clippy::similar_names",
    -- "-W",
    -- "clippy::cargo_common_metadata",
    -- "-W",
    -- "clippy::multiple_crate_versions",
    -- "-W",
    -- "clippy::uninlined_format_args",

    -- "-W",
    -- "clippy::print_stdout",
    -- "-W",
    -- "clippy::print_stderr",

    -- "-W",
    -- "clippy::use_debug",
    -- "-W",
    -- "clippy::std_instead_of_core",
    -- "-W",
    -- "clippy::std_instead_of_alloc",

    "-W",
    "clippy::alloc_instead_of_core",
    "-W",
    "clippy::allow_attributes",
    "-W",
    "clippy::allow_attributes_without_reason",
    -- "-W",
    -- "clippy::arithmetic_side_effects",

    "-W",
    "clippy::checked_conversions",
    -- "-W",
    -- "clippy::tuple_array_conversions",

    "-W",
    "clippy::as_underscore",

    -- "-W",
    -- "clippy::assertions_on_result_states",
    -- "-W",
    -- "clippy::big_endian_bytes",
    -- "-W",
    -- "clippy::host_endian_bytes",
    -- "-W",
    -- "clippy::little_endian_bytes",

    "-W",
    "clippy::branches_sharing_code",
    "-W",
    "clippy::case_sensitive_file_extension_comparisons",

    -- "-W",
    -- "clippy::as_conversions",
    -- "-W",
    -- "clippy::cast_lossless",
    -- "-W",
    -- "clippy::cast_possible_truncation",
    -- "-W",
    -- "clippy::cast_possible_wrap",
    -- "-W",
    -- "clippy::cast_precision_loss",
    -- "-W",
    -- "clippy::cast_sign_loss",

    "-W",
    "clippy::clear_with_drain",
    -- "-W",
    -- "clippy::cognitive_complexity",
    "-W",
    "clippy::collection_is_never_read",
    "-W",
    "clippy::copy_iterator",
    "-W",
    "clippy::create_dir",
    "-W",
    "clippy::debug_assert_with_mut_call",
    "-W",
    "clippy::default_union_representation",
    "-W",
    "clippy::deref_by_slicing",
    "-W",
    "clippy::derive_partial_eq_without_eq",
    "-W",
    "clippy::disallowed_script_idents",

    -- "-W",
    -- "clippy::float_arithmetic",
    "-W",
    "clippy::float_cmp",
    "-W",
    "clippy::float_cmp_const",
    "-W",
    "clippy::lossy_float_literal",

    "-W",
    "clippy::explicit_deref_methods",
    "-W",
    "clippy::explicit_into_iter_loop",
    "-W",
    "clippy::explicit_iter_loop",

    "-W",
    "clippy::rc_buffer",
    "-W",
    "clippy::rc_mutex",
    "-W",
    "clippy::mutex_atomic",
    "-W",
    "clippy::mutex_integer",
    -- "-W",
    -- "clippy::integer_division",
    "-W",
    "clippy::invalid_upcast_comparisons",

    "-W",
    "clippy::linkedlist",

    "-W",
    "clippy::match_bool",
    "-W",
    "clippy::match_on_vec_items",
    -- "-W",
    -- "clippy::match_same_arms",
    "-W",
    "clippy::match_wild_err_arm",
    -- "-W",
    -- "clippy::match_wildcard_for_single_variants",

    "-W",
    "clippy::needless_bitwise_bool",
    "-W",
    "clippy::needless_collect",
    "-W",
    "clippy::needless_continue",
    "-W",
    "clippy::needless_for_each",
    "-W",
    "clippy::needless_pass_by_value",

    "-W",
    "clippy::range_minus_one",
    "-W",
    "clippy::range_plus_one",

    "-W",
    "clippy::semicolon_if_nothing_returned",
    "-W",
    "clippy::semicolon_inside_block",
    "-W",
    "clippy::semicolon_outside_block",

    "-W",
    "clippy::stable_sort_primitive",

    "-W",
    "clippy::unnecessary_box_returns",
    "-W",
    "clippy::unnecessary_join",
    "-W",
    "clippy::unnecessary_safety_comment",
    "-W",
    "clippy::unnecessary_self_imports",
    "-W",
    "clippy::unnecessary_struct_initialization",
    "-W",
    "clippy::unnecessary_wraps",

    "-W",
    "clippy::cloned_instead_of_copied",

    "-W",
    "clippy::unused_async",
    "-W",
    "clippy::unused_peekable",
    "-W",
    "clippy::unused_rounding",
    "-W",
    "clippy::unused_self",
    "-W",
    "clippy::use_self",

    "-W",
    "clippy::verbose_file_reads",
    "-W",
    "clippy::verbose_bit_mask",

    -- "-W",
    -- "clippy::unreachable",
    -- "-W",
    -- "clippy::todo",
    -- "-W",
    -- "clippy::dbg_macro",
    -- "-W",
    -- "clippy::unimplemented",

    "-W",
    "clippy::unneeded_field_pattern",
    "-W",
    "clippy::unnested_or_patterns",

    "-W",
    "clippy::type_repetition_in_bounds",
    "-W",
    "clippy::unchecked_duration_subtraction",
    "-W",
    "clippy::unicode_not_nfc",

    "-W",
    "clippy::missing_const_for_fn",

    "-W",
    "clippy::mut_mut",
    "-W",
    "clippy::filetype_is_file",
    -- "-W",
    -- "clippy::future_not_send",
    "-W",
    "clippy::readonly_write_lock",

    -- "-W",
    -- "clippy::shadow_unrelated",
    -- "-W",
    -- "clippy::shadow_reuse",
    -- "-W",
    -- "clippy::shadow_same",

    "-W",
    "clippy::try_err",

    "-W",
    "clippy::same_functions_in_if_condition",
    "-W",
    "clippy::same_name_method",

    "-W",
    "clippy::large_digit_groups",
    "-W",
    "clippy::large_futures",
    "-W",
    "clippy::large_include_file",
    "-W",
    "clippy::large_stack_arrays",
    "-W",
    "clippy::large_stack_frames",
    "-W",
    "clippy::large_types_passed_by_value",

    "-W",
    "clippy::index_refutable_slice",
    -- "-W",
    -- "clippy::indexing_slicing",

    "-W",
    "clippy::mem_forget",
    "-W",
    "clippy::empty_drop",
    "-W",
    "clippy::empty_line_after_outer_attr",
    "-W",
    "clippy::empty_structs_with_brackets",
    "-W",
    "clippy::empty_enum",

    "-W",
    "clippy::enum_glob_use",
    "-W",
    "clippy::error_impl_error",
    "-W",
    "clippy::exit",

    "-W",
    "clippy::ignored_unit_patterns",

    "-W",
    "clippy::trait_duplication_in_bounds",
    "-W",
    "clippy::default_trait_access",
    "-W",
    "clippy::impl_trait_in_params",

    "-W",
    "clippy::trivial_regex",
    "-W",
    "clippy::trivially_copy_pass_by_ref",

    "-W",
    "clippy::cast_ptr_alignment",
    "-W",
    "clippy::borrow_as_ptr",
    "-W",
    "clippy::as_ptr_cast_mut",
    "-W",
    "clippy::clone_on_ref_ptr",
    "-W",
    "clippy::ptr_as_ptr",
    "-W",
    "clippy::ptr_cast_constness",
    "-W",
    "clippy::transmute_ptr_to_ptr",

    -- "-W",
    -- "clippy::tests_outside_test_module",

    "-W",
    "clippy::panic",
    "-W",
    "clippy::panic_in_result_fn",

    "-W",
    "clippy::suboptimal_flops",

    -- "-W",
    -- "clippy::struct_excessive_bools",

    "-W",
    "clippy::should_panic_without_expect",
    -- "-W",
    -- "clippy::significant_drop_in_scrutinee",
    "-W",
    "clippy::significant_drop_tightening",

    -- "-W",
    -- "clippy::pub_use",
    -- "-W",
    -- "clippy::pub_with_shorthand",
    "-W",
    "clippy::pub_without_shorthand",

    "-W",
    "clippy::ref_binding_to_reference",
    "-W",
    "clippy::ref_option_ref",
    "-W",
    "clippy::ref_patterns",
    "-W",
    "clippy::rest_pat_in_fully_bound_structs",
    -- "-W",
    -- "clippy::self_named_module_files",

    "-W",
    "clippy::implicit_hasher",
    -- "-W",
    -- "clippy::implicit_return",
    "-W",
    "clippy::implicit_clone",
}
