-- • {val}    Highlight definition map, accepts the following keys:
--            • fg (or foreground): color name or "#RRGGBB", see note.
--            • bg (or background): color name or "#RRGGBB", see note.
--            • sp (or special): color name or "#RRGGBB"
--            • blend: integer between 0 and 100
--            • bold: boolean
--            • standout: boolean
--            • underline: boolean
--            • undercurl: boolean
--            • underdouble: boolean
--            • underdotted: boolean
--            • underdashed: boolean
--            • strikethrough: boolean
--            • italic: boolean
--            • reverse: boolean
--            • nocombine: boolean
--            • link: name of another highlight group to link to, see
--              |:hi-link|.
--            • default: Don't override existing definition |:hi-default|
--            • ctermfg: Sets foreground of cterm color |ctermfg|
--            • ctermbg: Sets background of cterm color |ctermbg|
--            • cterm: cterm attribute map, like |highlight-args|. If not
--              set, cterm attributes will match those from the attribute
--              map documented above.
vim.api.nvim_set_hl(0, "Normal", {})
