# $lock = ~/.linuxConfig/wayland/swaylock/swaylock.sh
$lock = hyprlock

general {
    lock_cmd = $lock                              # dbus/sysd lock command (loginctl lock-session)
    # unlock_cmd = notify-send "unlock!"            # same as above, but unlock
    before_sleep_cmd = $lock                      # command ran before sleep
    # after_sleep_cmd = kanshi        # command ran after sleep
    # after_sleep_cmd = hyprctl reload        # command ran after sleep
    ignore_dbus_inhibit = false                   # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}

listener {
    timeout = 3600                                # in seconds
    on-timeout = systemctl suspend # command to run when timeout has passed
    # on-resume = notify-send "Welcome back!"       # command to run when activity is detected after timeout has fired.
}

listener {
    timeout = 1200                                # in seconds
    on-timeout = hyprctl dispatch dpms off             # command to run when timeout has passed
    # on-resume = notify-send "Welcome back!"       # command to run when activity is detected after timeout has fired.
}

# lockscreen
listener {
    timeout = 900                                # in seconds
    on-timeout = $lock                            # command to run when timeout has passed
    # on-resume = notify-send "Welcome back!"       # command to run when activity is detected after timeout has fired.
}
