# url 里填写自己的订阅,名称不能重复
proxy-providers:
  yiyuan:
    url: ""
    type: http
    interval: 43200
    health-check:
      {
        enable: true,
        url: "https://www.gstatic.com/generate_204",
        interval: 300,
      }
    override:
      additional-prefix: "[yiyuan]"

  sanfen:
    url: ""
    type: http
    interval: 43200
    health-check:
      {
        enable: true,
        url: "https://www.gstatic.com/generate_204",
        interval: 300,
      }
    override:
      additional-prefix: "[sanfen]"

  fny:
    url: ""
    type: http
    interval: 43200
    health-check:
      {
        enable: true,
        url: "https://www.gstatic.com/generate_204",
        interval: 300,
      }
    override:
      additional-prefix: "[fny]"

  pq:
    url: ""
    type: http
    interval: 43200
    health-check:
      {
        enable: true,
        url: "https://www.gstatic.com/generate_204",
        interval: 300,
      }
    override:
      additional-prefix: "[pq]"

proxies:
  - name: "直连"
    type: direct
    udp: true

mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"
  asn: "https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query
    "geosite:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"

proxy-groups:
  - name: Google
    type: url-test
    interval: 100
    strategy: sticky-sessions
    tolerance: 100
    proxies:
      [香港, 台湾, 新加坡, 美国, Excellent]

  - name: 巴哈姆特
    type: url-test
    interval: 100
    strategy: sticky-sessions
    tolerance: 100
    proxies:
      [台湾]

  - name: Github
    type: url-test
    interval: 100
    strategy: sticky-sessions
    tolerance: 100
    proxies:
      [香港, 台湾, 新加坡, 美国, Excellent]

  - name: 国内
    type: select
    proxies:
      [直连]

  - name: Excellent
    type: url-test
    interval: 100
    strategy: sticky-sessions
    tolerance: 100
    exclude-filter: "日本"
    include-all: true
    filter: "(?i)(pq|fny)"

  - name: 香港
    type: url-test
    interval: 100
    strategy: sticky-sessions
    tolerance: 100
    include-all: true
    exclude-filter: "(?i)(sanfen|yiyuan)"
    filter: "(?i)港|hk|hongkong|hong kong"

  - name: 台湾
    type: url-test
    interval: 100
    strategy: sticky-sessions
    tolerance: 100
    include-all: true
    exclude-filter: "(?i)(sanfen|yiyuan)"
    filter: "(?i)台|tw|taiwan"

  - name: 美国
    type: url-test
    interval: 100
    strategy: sticky-sessions
    tolerance: 100
    include-all: true
    exclude-filter: "(?i)(sanfen|yiyuan)"
    filter: "(?i)美|us|unitedstates|united states"

  - name: 新加坡
    type: url-test
    interval: 100
    strategy: sticky-sessions
    tolerance: 100
    include-all: true
    exclude-filter: "(?i)(sanfen|yiyuan)"
    filter: "(?i)(新|sg|singapore)"

  - name: 日本
    type: url-test
    interval: 100
    strategy: sticky-sessions
    tolerance: 100
    include-all: true
    exclude-filter: "(?i)(sanfen|yiyuan)"
    filter: "(?i)(日本|jp|japan)"

  - name: 大流量
    type: url-test
    strategy: round-robin
    tolerance: 100
    include-all: true
    filter: "(?i)(sanfen|yiyuan)"

  - name: 自动选择
    type: url-test
    interval: 100
    exclude-filter: "(?i)(直连|日本)"
    include-all: true
    tolerance: 100

rules:
  - GEOIP,lan,直连,no-resolve

  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,apple,DIRECT
  - DOMAIN,discussions.apple.com,DIRECT
  - DOMAIN,apps.apple.com,DIRECT
  - DOMAIN,discussionschinese.apple.com,DIRECT

  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,private,DIRECT
  - GEOSITE,pixiv,Google
  - GEOSITE,category-scholar-!cn,Google
  - GEOSITE,microsoft@cn,DIRECT
  # - GEOSITE,geolocation-!cn,PROXY
  - GEOSITE,github,Github
  - GEOSITE,twitter,大流量
  - GEOSITE,youtube,大流量
  - GEOSITE,google,Google
  - GEOSITE,telegram,大流量
  - GEOSITE,netflix,大流量
  # - GEOSITE,bilibili,哔哩哔哩
  - GEOSITE,bahamut,巴哈姆特
  - GEOSITE,spotify,Google
  - GEOSITE,CN,DIRECT

  - GEOIP,google,Google
  - GEOIP,netflix,大流量
  - GEOIP,telegram,大流量
  - GEOIP,twitter,大流量
  - GEOIP,CN,DIRECT

  # - DOMAIN,outlook.com,国内
  # - DOMAIN,reddit.com,Google
  # - DST-PORT,80/8080/443/8443,PROXY
  - MATCH,Google
